### ISSUE TITLE
Doubt SLUCM bug in WRF4.5

### ISSUE THREAD

**Issue by jesusff** [CORDEX-WRF-community/fps-urb-rcc#4]
I reproduce here an issue that was raised via e-mail, in order not to lose it and keep track.

On 5/12/23 13:05, Anahí wrote:
> This is Anahí from CUNI. During the FPS WRF group meeting today you mentioned that it seems that SLUCM has a bug in this new version. I ran some long-term simulations with that urban scheme, and I have seen that, compared to the using a non-urban scheme, the differences in T2 and Q2 look ok but not in the wind speed at 10m (instead of showing smaller values for the SLUCM scheme compared to the nourban, I get higher values). When my colleagues ran it with previous versions of the model, it was working well, so when I heard you it came to my mind this might be connected to that possible bug you mentioned.  I wanted to ask you if you know more details about it, i.e., where the bug is or which variables it affects, mainly.
> 
> Thank you so much for your time.

On 5/12/23 17:33, Sun wrote:
> We are exploring about it as well.
> I could not get “SF_URBAN_PHYSICS = 1” to run after V4.3.
> https://forum.mmm.ucar.edu/threads/resolved-wrf-single-layer-ucm-crashed.13453
> It seems to be related to the numerical stability. 

On 6/12/23 11:06, Anahí wrote:
> Thank you very much for your reply. It is interesting because I could run it without problem after changing the TS_SCHEME from 1 to 2, but the values of the horizontal velocity at 10m are weird compared to the runs without urban scheme and changing the urban areas for rural. Let's see if someone else has the same issue and knows how to solve it.

On 8/12/23 9:13, Sun wrote:
> Changing the TS_SCHEME from 1 to 2 implies that the method we employ to parameterise the ground heat flux could be crucial.
> When I examine the latent and sensible heat fluxes in relation to the Bowen ratio, I am always uncertain about the simulation in an urban environment.

On 8/12/23 11:14, Josipa wrote:
> Thank you for opening this discussion. We are struggling with this scheme for some time as well. We tried to run the simulation with SLUCM, and It crashes always at some timesteps. I am trying now for a different domain size, but it crashes at the beginning, at the 1:15 timestep. I was testing with different lowest level, with different Land cover (as SLUCM uses LANDUSEF instead LU_INDEX), but it never worked out. For the Paris-3 domain test runs, I managed to get it running few hours, and then it crashed. I have not tried to test changing TS_SCHEME, but yes - it seems that it affects the surface energy balance, which is a lower boundary for the surface layer and PBL schemes, and for sure may affect the diagnostics like surface wind. 
>
> I would agree with Sun, and would say this could be related to the stability. Here is something I have just run into, but I have not tried it yet: It might be a solution to try to test new threshold values in the code (check her here https://forum.mmm.ucar.edu/threads/resolved-wrf-single-layer-ucm-crashed.13453/) and maybe to avoid changing TS_SCHEME option. Has anyone already tried this?

**Comment by jesusff** [comment]
Here
https://forum.mmm.ucar.edu/threads/unrealistic-tsk-in-wrf-slucm.13058
they describe the same behaviour as @yoselita is describing (crash after some time running). They also ended up solving it by changing the TS_SCHEME to 2. However, one of the respondents had no problem using the same input data and config. It might be a problem dependent on the compilation of the model (level of optimization or who knows), that affects the convergence of the non-linear equation iterative solving method in the 4-layer model (TS_SCHEME = 1). The changes in thresholds proposed in the other forum entry you mention, also seem related to the precision of the comparisons, which can be dependent on compiler flags.

In any case, if this scheme is so sensitive to these numerical issues, we might consider switching to TS_SCHEME = 2. How weird are those 10m wind results with TS_SCHEME = 2, Anahí? Could you share some plots?

**Comment by anvipra** [comment]
Hi,

Sure. Here is the plot I did to see the differences between different urban schemes. The values show the seasonal average of wind at 10m for DJF averaged over the whole 10-year period. The graph on the left shows the difference between the values obtained with the SLUCM scheme and the NOURBAN scheme (sf_urban_physics=0 with urban land use replaced by rural one ).

![seasonal_NU_and_differences_W10_DJF](https://github.com/CORDEX-WRF-community/fps-urb-rcc/assets/153728948/b687cefd-5545-497c-b6b3-11fb4ff5c998)

**Comment by jesusff** [comment]
yes, this increased wind speed over cities is quite suspicious. Some time ago, Alberto warned us on:
> when using SLUCM (Single layer urban Canopy model, sf_urban=1), the variable T2 is a log interpolation at 2m above roof level (or more precisely above the displacement height). It is not the temperature at 2m above street level
I guess that near-surface wind might also be above the buildings in SLUCM and, thus, not really comparable to rural areas. Could you check how the wind speed looks like in the lowest model level instead of the 10m diagnostic?

Maybe @andreazonato can provide some insight here

**Comment by andreazonato** [comment]
Sorry but I cannot help with SLUCM. But pretty strange. Ayway, you should look in module_sf_urban.F how U10_URB,V10_URB are calculated

Andrea

**Comment by anvipra** [comment]
@jesusff and @andreazonato, thank you very much for your suggestions. I will check it and come back to you once I have the results.

**Comment by anvipra** [comment]
I plotted the differences in the horizontal wind speed at the lowest level and now it looks as it should.
![Hor_vel_SLUCM-NU DJF](https://github.com/CORDEX-WRF-community/fps-urb-rcc/assets/153728948/a49bff21-e62b-4b07-a638-581301cfe6d7)
